---
title: "Cochrane"
author: "Simon Schwab"
date: "09 Jan 2019"
output:
  pdf_document: default
  html_notebook: default
---

# Vars
```{r}
PATH_HOME = path.expand("~") # user home
PATH = file.path(PATH_HOME, 'thesis/cochrane')
```

# Read data
```{r}
source(file.path(PATH, 'prepare.R'))
```

# Inspect data frame
```{r}
str(madata)

names(madata)
```

# Inspect single study
https://www.cochranelibrary.com/cdsr/doi/10.1002/14651858.CD012713.pub2/full
```{r}
madata[madata$file.nr==6242, ]


```


```{r}
# check first entry, corresponding to first Cochrane review:
madata[madata$file.nr==1, ]

# example: show Richer-et-al review's data
# (see http://doi.org/10.1002/14651858.CD005220.pub2):
madata[madata$file.name=="MYdwnld_CD005220StatsDataOnly_Version2.csv", c(2,5,7,10,12)]

# show outcome measures and their frequencies:
t(t(sort(table(madata$outcome.measure), decreasing=TRUE)))

# non-zero entries for event counts only for RR/OR/RD/HR outcomes: 
t(t(sort(table(madata$outcome.measure[(madata$events1>0) | (madata$events2>0)]),dec=TRUE)))

# binary outcomes' names:
outcomenames <- unique(madata$outcome.measure[(madata$events1>0) | (madata$events2>0)])
# studies with binary outcomes:
binstudies <- is.element(madata$outcome.measure, outcomenames)
# fraction of binary outcomes:
mean(binstudies)  # 67%
# fraction of zero counts among binary outcomes:
mean((madata$events1[binstudies] == 0)
     | (madata$events1[binstudies] == madata$total1[binstudies])
     | (madata$events2[binstudies] == 0)
     | (madata$events2[binstudies] == madata$total2[binstudies]))
#  26 % (!)


##########################################
# distribution of analysis sizes;
# overall analyses:
tab1 <- table(table(paste(madata$file.nr, madata$comparison.nr, madata$outcome.nr, sep=".")))
tab1 <- c(tab1[1:15], ">15"=sum(tab1[-(1:15)]))
tab1 <- tab1/sum(tab1)
round(cbind("prob"=tab1, "cumulative"=cumsum(tab1)),3)
barplot(tab1, col="red3")

# subgroup analyses:
tab2 <- table(table(paste(madata$file.nr, madata$comparison.nr, madata$outcome.nr, madata$subgroup.nr, sep=".")))
tab2 <- c(tab2[1:15], ">15"=sum(tab2[-(1:15)]))
tab2 <- tab2/sum(tab2)
round(cbind("prob"=tab2, "cumulative"=cumsum(tab2)),3)
barplot(tab2, col="blue3")

# both analysis types:
barplot(rbind(tab1, tab2), beside=TRUE, col=c("red3","blue3"),
        xlab="number of studies included", ylab="frequency")
legend("topright", c("overall analyses","subgroup analyses"),
       pch=15, col=c("red3","blue3"))


```

